# Generated by Django 5.0.2 on 2024-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=100)),
                ('prazo', models.TextField(max_length=100)),
            ],
        ),
    ]
