# Generated by Django 5.0.2 on 2024-04-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task_genius', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefas',
            new_name='Tarefa',
        ),
    ]
