# Generated by Django 5.0.2 on 2024-04-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task_genius', '0004_alter_tarefa_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.CharField(max_length=100),
        ),
    ]
